name: test
on: 
  push:
    branches:
      - main  # 必要なブランチを指定

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      # リポジトリをクローン
      - uses: actions/checkout@v2

      # 必要なディレクトリ構造を作成
      - name: Prepare workspace
        run: |
          mkdir -p /root/ros2_ws/src
          rsync -av ./ /root/ros2_ws/src/mypkg/

      # 必要な依存関係のインストール
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3-rosdep
          rosdep init
          rosdep update
          rosdep install --from-paths /root/ros2_ws/src --ignore-src -r -y

      # ビルドとテストの実行
      - name: Build and test
        run: |
          cd /root/ros2_ws
          colcon build
          bash -xv ./src/mypkg/test/test.bash /root

